# Configuration for development environment
server:
  port: ${SERVER_PORT:8081}

# Database configurations
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Hikari configuration
#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      leak-detection-threshold: 0
#      initialization-fail-timeout: -1

# Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

# Logging related configuration
logging:
  level:
    org.springframework.security: debug

# JWT configuration (CUSTOM)
security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER:com.common.auth}
      access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
      refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
      refresh-token-cookie-name: ${JWT_REFRESH_TOKEN_COOKIE_NAME:refreshToken}
      cookie-secure: ${JWT_COOKIE_SECURE:true}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT-COOKIE-SAME-SITE:lax}

